spring:
  application.name: Your Conf Platform
  flyway.enabled: true
management:
  endpoint.health.show-details: always
  endpoints.web:
    path-mapping.prometheus: /metrics
    base-path: /internal
    exposure.include: "health, prometheus"

server:
  tomcat:
    accesslog:
      enabled: true